### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by YevheniiaYaroshevska** [YevheniiaYaroshevska/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by YaroshevskaYevheniia** [comment]
Team player with multi-tasking skills and apt learning, interested in the position of
Manual Software QA Tester. Seeking to work for a company that appreciates
excellence and hard work.
