### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by YevheniiaYaroshevska** [YevheniiaYaroshevska/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by YaroshevskaYevheniia** [comment]
Location: Cherkassy city
E-mail: yaroshevskayevheniia@gmail.com
Phone: +38(097) 671-24-67
LinkedIn: yaroshevskayevheniia
