### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by YevheniiaYaroshevska** [YevheniiaYaroshevska/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by YaroshevskaYevheniia** [comment]
Master's Degree in Engineering - Cherkasy State Technological University - Devices and Systems of Precise Mechanics - (2009 - 2015)
"Quality assurance" course -  Cherkasy company "Andersen" (10/2020 - 11/2020)
Design engineer - Research and production complex "PHOTOPRYLAD" (01/12/2014 - Present)
